# Generated by Django 4.1.1 on 2022-09-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='shortened_link',
            field=models.CharField(default='DHgE8', max_length=100),
        ),
    ]
