# Generated by Django 4.1.1 on 2022-09-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_links_shortened_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='shortened_link',
            field=models.CharField(default='rULqB', max_length=100),
        ),
    ]
